#cloud-config
package_update: true
package_upgrade: false
timezone: UTC
users:
  - default
  - name: manager
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
chpasswd:
  expire: false
  users:
    - name: manager
      password: <runtime-secret>
ssh_pwauth: true
